### ISSUE TITLE
Latest tm2 release breaks plugin

### ISSUE THREAD

**Issue by rkingon** [Mr0grog/editorconfig-textmate#24]
I know this isn't your fault! But, the latest TextMate version 2.0-rc.1 release breaks this plugin.

Any chance you're able to look at it?

I unfortunately have no knowledge on tm plugins, or I would love to attempt contributing w/ a PR

**Comment by Mr0grog** [comment]
Hmmm, looking at the log output quickly, it seems like there’s some kind of timing issue—it’s reading the settings for the file being switched *away from* instead of the file you are switching *to.*

This is probably some change in timing or how things are ordered in TextMate and it seems like we’re getting the wrong file name in `NSView -setDocument:` here: https://github.com/Mr0grog/editorconfig-textmate/blob/master/source/additions/NSView%2BEditorConfig.m#L23

Not sure I will have time today to get to this (lots of work), but if that info above can help you get some idea where to

**Comment by Mr0grog** [comment]
Also looks like the document object being set in that method is now an ObjC class (was C++ last time I was working on this, long ago) that you should be able to grab a `path` property from: https://github.com/textmate/textmate/blob/master/Frameworks/document/src/OakDocument.h#L51

Using that, if it works as expected, would vastly de-hackify the code here ;)

**Comment by rkingon** [comment]
thanks for the quick response! I think your presumption might be right -- the delayed switch. TM is supposed to at least hold your personal setting for a file type, but in this case it actually does appear to be switching to my editor config settings but a file too late!

**Comment by rkingon** [comment]
I just verified this by switching to a coffee file from an html, it held html -- then went to yet another coffee file and it brought in my coffee settings. then switched to an html, it retained the coffee, then to another html and it picked up the setting

**Comment by Mr0grog** [comment]
@rkingon I found some time to do a quick fix for this. Do you mind trying the 0.2.6-beta release and letting me know if it solves the issue for you? https://github.com/Mr0grog/editorconfig-textmate/releases/tag/0.2.6-beta

**Comment by rkingon** [comment]
It works!!

**Comment by rkingon** [comment]
Thank you for banging this out man, truely awesome!

**Comment by Mr0grog** [comment]
No problem. You can also get the production build on the releases page now (not really any different except that it logs less).
