### ISSUE TITLE
Textmate 2 broken?

### ISSUE THREAD

**Issue by mnot** [Mr0grog/editorconfig-textmate#38]
It seems like the recent release of TextMate 2 has broken the module; I've tried reinstalling, but the `.editorconfig` doesn't seem to be applied (it was previously).

**Comment by Mr0grog** [comment]
Yeah, I noticed this recently, too. It looks like a recent release added support for MacOS’s runtime hardening, but didn’t make an exception for third-party plugins! (i.e. they set it up so the system will prevent TextMate from loading code bundles that aren’t signed by Macromates or by Apple. So even if I properly sign the plug-in, MacOS will prevent it from loading.)

I sent a note about it to the mailing list, but haven’t heard back yet: https://lists.macromates.com/textmate/2019-September/041170.html

**Comment by Mr0grog** [comment]
Update! TextMate added the entitlement and the plugin works again if you install the latest *test* version of TextMate. (See instructions in the mailing list discussion here: https://lists.macromates.com/textmate/2019-October/041189.html)

I’m not sure when a normal release will ship with the fix, but hopefully soon. :)

**Comment by we3geeks** [comment]
I'm on macOS 10.15.1 and TextMate 2.0.3 is showing something similar (although the wording of the dialog is slightly different from what's described on the mailing list thread) when I start it after copying the plugin to `~/Library/Application Support/TextMate/PlugIns`. It shows a dialog with the following messages:

"editorconfig-textmate.tmplugin" cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
Safari downloaded this today at 5:14 AM from github-production-release-asset-2e65be.s3.amazonaws.coming

[Move to Trash] [Cancel]

Selecting "Cancel" causes the same dialog to appear again, then TextMate starts. I don't get this behavior on my macOS 10.14.x system with the same version of TextMate.

I'm assuming this is likely still something on the TextMate side?

**Comment by Mr0grog** [comment]
Ah! No, at this point it’s on my side. I thought I had published a bundle that’s been signed (even with the changes in TM 2.0.3, the plugin still has to be signed — the change is just that it doesn’t have to be signed by Macromates), but it looks like I never got that released!

I am at a conference the rest of this week, but will try and get an update posted this weekend. Sorry to be behind the ball on this 😬

**Comment by we3geeks** [comment]
@Mr0grog No worries, and thanks for the quick follow-up.

**Comment by Mr0grog** [comment]
@mnot/@we3geeks/anyone else watching this thread, would you please download v0.4.0b1 and see if it works for you? https://github.com/Mr0grog/editorconfig-textmate/releases/tag/v0.4.0b1

**Comment by mnot** [comment]
Still getting this when textmate is relaunched:

<img width="425" alt="Screen Shot 2019-11-11 at 6 12 14 pm" src="https://user-images.githubusercontent.com/74384/68568143-e15cd700-04ae-11ea-9bd1-03410069e528.png">

**Comment by nsommer** [comment]
Same for me, also still get the error dialogue.

**Comment by we3geeks** [comment]
Same here, as well.

**Comment by Mr0grog** [comment]
Alright, I think I’ve got this fixed. [The v0.4.0b1 release](https://github.com/Mr0grog/editorconfig-textmate/releases/tag/v0.4.0b1) has a new file attached to it: `editorconfig-textmate-0.4.0b1-notarized.tmplugin.zip`. Can you please try that? (Note you may need to manually clean out the old plugin from `~/Library/Application Support/TextMate/PlugIns` first.)

^ It looks like notarization (not just signing) became required on Catalina, and I haven’t upgraded to Catalina yet, which is why I thought it was good to go but it didn’t work for any of you.

**Comment by mnot** [comment]
It works!

**Comment by we3geeks** [comment]
Confirmed. @Mr0grog, thank you!

**Comment by Mr0grog** [comment]
🎉 Thanks for testing, and sorry to have been a little slow to get this fixed.
