### ISSUE TITLE
Support for trim_trailing_whitespace and insert_final_newline

### ISSUE THREAD

**Issue by johan** [Mr0grog/editorconfig-textmate#7]
I don't have much personal need for the `end_of_line` feature, but I dearly miss  `insert_final_newline` and `trim_trailing_whitespace`. My own main use case for `.editorconfig` is to minimize diff noise in commits between people that check in not-really-changes to files / lines with respect to trailing whitespace, and these really help.

Are either planned for some happy day? :-) If not, is the rough implementation sketch for adding them to tweak `updateWindow` in `source/EditorConfig.m` to also do the work required for the missing config parameters?

**Comment by Mr0grog** [comment]
If anybody who was interested in this is still using TextMate these days, I’ve posted an alpha build that supports these features (TextMate 2 only): https://github.com/Mr0grog/editorconfig-textmate/releases/tag/v0.3.0-alpha

There’s a little bit of a caveat with respect to selections (more details on the release page). Please post back here and re-open the issue if that issue is a problem for you.
